const fs = require('fs');
const path = require('path');

// Raw user list pasted in the prompt
const userPlugins = [
  { raw: "UAD elysia karacter Stereo Saturator: Demo not started" },
  { raw: "UAD Black Box Analog Design HG-2: Demo not started" },
  { raw: "UAD elysia alpha compressor V2: Demo not started" },
  { raw: "UAD SPL Vitalizer MK3-T: Demo not started" },
  { raw: "UAD Shadow Hills Mastering Compressor Class A: Demo not started" },
  { raw: "UAD Maag Audio EQ4 MS: Demo not started" },
  { raw: "UAD A-Type Multiband Enhancer: Demo not started" },
  { raw: "UAD LA-6176 Signature Channel Strip: Authorized for all devices" },
  { raw: "UAD Antares Auto-Tune Realtime X: Authorized for all devices" },
  { raw: "UAD Hemisphere Mic Collection: Demo not started" },
  { raw: "UAD C-Suite C-Max Limiter: Demo not started" },
  { raw: "UAD Hitsville Reverb Chambers: Authorized for all devices" },
  { raw: "UAD C-Suite C-Axe Guitar Noise Suppressor: Demo not started" },
  { raw: "UAD Hitsville EQ Collection: Authorized for all devices" },
  { raw: "UAD AMS DMX 15-80 S Digital Delay and Pitch Shifter: Demo expired" },
  { raw: "UAD Manley Reference Microphone Preamplifier: Authorized for all devices" },
  { raw: "UAD API Vision Channel Strip Collection: Authorized for all devices" },
  { raw: "UAD API Preamp: Authorized for all devices" },
  { raw: "UAD C-Suite C-Vox Noise and Ambience Reduction: Authorized for all devices" },
  { raw: "UAD Neve Dynamics Collection: Authorized for all devices" },
  { raw: "UAD Neve 1084 Preamp and EQ: Authorized for all devices" },
  { raw: "UAD Avalon VT-737sp Channel Strip: Authorized for all devices" },
  { raw: "UAD Oxford SuprEsser DS: Authorized for all devices" },
  { raw: "UAD Diezel VH4 Amplifier: Demo not started" },
  { raw: "UAD Auto-Tune Realtime Access: Authorized for all devices" },
  { raw: "UAD UA 175B and 176 Tube Compressor Collection: Authorized for all devices" },
  { raw: "UAD Capitol Chambers: Authorized for all devices" },
  { raw: "UAD Tube-Tech CL 1B mk II: Authorized for all devices" },
  { raw: "UAD V76 Preamp: Authorized for all devices" },
  { raw: "UAD Auto-Tune Realtime Advanced: Authorized for all devices" },
  { raw: "UAD Diezel Herbert Amplifier: Demo not started" },
  { raw: "UAD Lexicon 480L Digital Reverb and Effects: Authorized for all devices" },
  { raw: "UAD Softube Vocoder: Authorized for all devices" },
  { raw: "UAD AMS Neve DFC Channel Strip: Authorized for all devices" },
  { raw: "UAD Suhr SE100 Amplifier: Demo not started" },
  { raw: "UAD bx_masterdesk Classic: Demo not started" },
  { raw: "UAD Century Tube Channel Strip: Authorized for all devices" },
  { raw: "UAD bx_masterdesk: Demo not started" },
  { raw: "UAD Suhr PT100 Amplifier: Demo not started" },
  { raw: "UAD Putnam Microphone Collection: Authorized for all devices" },
  { raw: "UAD Ampeg SVT-VR Classic Bass Amplifier: Authorized for all devices" },
  { raw: "UAD Neve Preamp: Authorized for all devices" },
  { raw: "UAD ADA Flanger: Demo not started" },
  { raw: "UAD Friedman Buxom Betty Amplifier: Demo not started" },
  { raw: "UAD Helios Type 69 Preamp and EQ Collection: Authorized for all devices" },
  { raw: "UAD Empirical Labs EL8 Distressor Compressor: Authorized for all devices" },
  { raw: "UAD Dytronics Tri-Stereo Chorus: Demo not started" },
  { raw: "UAD Gallien-Krueger 800RB Bass Amplifier: Demo not started" },
  { raw: "UAD Marshall Plexi Classic Amplifier: Authorized for all devices" },
  { raw: "UAD Ocean Way Microphone Collection: Authorized for all devices" },
  { raw: "UAD TS Overdrive: Authorized for all devices" },
  { raw: "UAD Korg SDD-3000 Digital Delay: Authorized for all devices" },
  { raw: "UAD Oxford Dynamic EQ: Demo not started" },
  { raw: "UAD Dytronics Cyclosonic Panner: Demo not started" },
  { raw: "UAD ENGL Savage 120 Guitar Amplifier: Demo not started" },
  { raw: "UAD AMS RMX16 Expanded Digital Reverb: Authorized for all devices" },
  { raw: "UAD Pure Plate Reverb: Authorized for all devices" },
  { raw: "UAD SSL 4000 G Bus Compressor Collection: Authorized for all devices" },
  { raw: "UAD Antares Auto-Tune Realtime: Authorized for all devices" },
  { raw: "UAD Eden WT800 Bass Amplifier: Demo not started" },
  { raw: "UAD Fuchs Train II Guitar Amplifier: Demo not started" },
  { raw: "UAD Moog Multimode Filter Collection: Authorized for all devices" },
  { raw: "UAD SSL 4000 E Channel Strip Collection: Authorized for all devices" },
  { raw: "UAD OTO Biscuit 8-bit Filter Effects: Demo not started" },
  { raw: "UAD Fuchs Overdrive Supreme 50 Amplifier: Demo not started" },
  { raw: "UAD bx_subsynth Subharmonic Synth: Demo not started" },
  { raw: "UAD API 2500 Bus Compressor: Authorized for all devices" },
  { raw: "UAD Sphere Mic Collection: Authorized for all devices" },
  { raw: "UAD Chandler Limited Zener Limiter: Demo not started" },
  { raw: "UAD ADA STD-1 Stereo Tapped Delay: Demo expired" },
  { raw: "UAD Manley VOXBOX Channel Strip: Authorized for all devices" },
  { raw: "UAD Ampeg B15N Bass Amplifier: Demo not started" },
  { raw: "UAD Galaxy Tape Echo: Authorized for all devices" },
  { raw: "UAD Studio D Chorus: Authorized for all devices" },
  { raw: "UAD Brigade Chorus: Authorized for all devices" },
  { raw: "UAD Fender 55 Tweed Deluxe Amplifier: Authorized for all devices" },
  { raw: "UAD Chandler Limited Curve Bender EQ: Demo not started" },
  { raw: "UAD Oxford Limiter V2: Demo not started" },
  { raw: "UAD Oxford Envolution Envelope Shaper: Demo not started" },
  { raw: "UAD bx_digital V3 EQ Collection: Authorized for all devices" },
  { raw: "UAD Marshall JMP 2203 Amplifier: Demo not started" },
  { raw: "UAD Oxide Tape Recorder: Authorized for all devices" },
  { raw: "UAD Eventide H910 Harmonizer: Demo expired" },
  { raw: "UAD Marshall Bluesbreaker 1962 Amplifier: Demo not started" },
  { raw: "UAD Marshall Silver Jubilee 2555 Amplifier: Demo not started" },
  { raw: "UAD AKG BX 20 Spring Reverb: Authorized for all devices" },
  { raw: "UAD Tube-Tech EQ Collection: Authorized for all devices" },
  { raw: "UAD Ampeg SVT-VR Bass Amplifier: Demo not started" },
  { raw: "UAD Ampeg SVT-3 Pro Bass Amplifier: Demo expired" },
  { raw: "UAD Neve 88RS Channel Strip Collection: Authorized for all devices" },
  { raw: "UAD Marshall Plexi Super Lead 1959 Amplifier: Demo not started" },
  { raw: "UAD Tube-Tech CL 1B Compressor: Authorized for all devices" },
  { raw: "UAD Ibanez Tube Screamer TS808 Overdrive: Demo not started" },
  { raw: "UAD Raw Distortion: Authorized for all devices" },
  { raw: "UAD Bermuda Triangle Distortion: Authorized for all devices" },
  { raw: "UAD Friedman Amplifiers Collection: Demo not started" },
  { raw: "UAD Sound Machine Wood Works: Demo not started" },
  { raw: "UAD Manley Variable Mu Limiter: Authorized for all devices" },
  { raw: "UAD Vertigo VSC-2 Compressor: Demo not started" },
  { raw: "UAD Vertigo VSM-3 Saturator: Demo not started" },
  { raw: "UAD Massenburg DesignWorks MDWEQ5 EQ: Authorized for all devices" },
  { raw: "UAD AMS RMX16 Digital Reverb: Authorized for all devices" },
  { raw: "UAD Summit Audio TLA-100A Compressor: Demo not started" },
  { raw: "UAD elysia alpha compressor: Demo not started" },
  { raw: "UAD elysia mpressor: Demo not started" },
  { raw: "UAD Thermionic Culture Vulture Distortion: Authorized for all devices" },
  { raw: "UAD Tonelux Tilt EQ: Demo not started" },
  { raw: "UAD Valley People Dyna-mite Dynamics: Demo expired" },
  { raw: "UAD Neve 1073 Preamp and EQ Collection: Authorized for all devices" },
  { raw: "UAD Chandler GAV19T Guitar Amplifier: Demo not started" },
  { raw: "UAD bx_refinement: Demo not started" },
  { raw: "UAD bx_saturator V2: Demo not started" },
  { raw: "UAD UA 610-A Tube Preamp and EQ: Authorized for all devices" },
  { raw: "UAD UA 610-B Tube Preamp and EQ: Authorized for all devices" },
  { raw: "UAD Dangerous BAX EQ Collection: Demo not started" },
  { raw: "UAD Fairchild Tube Limiter Collection: Authorized for all devices" },
  { raw: "UAD Maag EQ4 EQ: Demo not started" },
  { raw: "UAD API Vision Channel Strip Legacy: Authorized for all devices" },
  { raw: "UAD ENGL 646 VS Guitar Amplifier: Demo not started" },
  { raw: "UAD ENGL 765 RT Guitar Amplifier: Demo not started" },
  { raw: "UAD bx_tuner: Demo not started" },
  { raw: "UAD Pultec Passive EQ Collection: Authorized for all devices" },
  { raw: "UAD Millennia NSEQ-2 EQ: Demo not started" },
  { raw: "UAD Ocean Way Studios Room Modeler: Authorized for all devices" },
  { raw: "UAD Oxford Inflator: Authorized for all devices" },
  { raw: "UAD SPL TwinTube Saturation: Demo not started" },
  { raw: "UAD Teletronix LA-2A Leveler Collection: Authorized for all devices" },
  { raw: "UAD API 500 EQ Collection: Authorized for all devices" },
  { raw: "UAD Softube Vintage Amp Room: Demo not started" },
  { raw: "UAD Softube Metal Amp Room: Demo not started" },
  { raw: "UAD Softube Bass Amp Room: Demo not started" },
  { raw: "UAD Precision K-Stereo Ambience Recovery: Authorized for all devices" },
  { raw: "UAD Shadow Hills Mastering Compressor: Demo not started" },
  { raw: "UAD Oxford EQ: Demo not started" },
  { raw: "UAD UA 1176 Limiter Collection: Authorized for all devices" },
  { raw: "UAD MXR Flanger-Doubler: Authorized for all devices" },
  { raw: "UAD Little Labs VOG Bass Enhancer: Authorized for all devices" },
  { raw: "UAD Ampex ATR-102 Tape Recorder: Authorized for all devices" },
  { raw: "UAD bx_digital V2 EQ: Authorized for all devices" },
  { raw: "UAD SPL Vitalizer MK2-T: Demo expired" },
  { raw: "UAD Lexicon 224 Digital Reverb: Authorized for all devices" },
  { raw: "UAD SSL 4000 E Legacy Channel Strip: Authorized for all devices" },
  { raw: "UAD SSL 4000 G Legacy Bus Compressor: Authorized for all devices" },
  { raw: "UAD Studer A800 Tape Recorder: Authorized for all devices" },
  { raw: "UAD EP-34 Tape Echo: Authorized for all devices" },
  { raw: "UAD Precision Enhancer Hz: Authorized for all devices" },
  { raw: "UAD Manley Massive Passive EQ Collection: Authorized for all devices" },
  { raw: "UAD Trident A-Range EQ: Authorized for all devices" },
  { raw: "UAD Empirical Labs EL7 FATSO Compressor: Authorized for all devices" },
  { raw: "UAD EMT 250 Digital Reverb: Authorized for all devices" },
  { raw: "UAD Neve 31102 EQ: Authorized for all devices" },
  { raw: "UAD 4K Buss Compressor: Demo not started" },
  { raw: "UAD 4K Channel Strip: Demo not started" },
  { raw: "UAD Cooper Time Cube Delay: Authorized for all devices" },
  { raw: "UAD Harrison 32C EQ: Authorized for all devices" },
  { raw: "UAD Little Labs IBP Phase Alignment: Authorized for all devices" },
  { raw: "UAD Moog Multimode Legacy Filter: Authorized for all devices" },
  { raw: "UAD Precision Enhancer kHz: Authorized for all devices" },
  { raw: "UAD dbx 160 Compressor: Authorized for all devices" },
  { raw: "UAD SPL Transient Designer: Demo not started" },
  { raw: "UAD Precision Buss Compressor: Authorized for all devices" },
  { raw: "UAD Precision De-Esser: Authorized for all devices" },
  { raw: "UAD Precision Maximizer: Authorized for all devices" },
  { raw: "UAD Teletronix LA-3A Audio Leveler: Authorized for all devices" },
  { raw: "UAD Neve 88RS Legacy Channel Strip: Authorized for all devices" },
  { raw: "UAD Helios Type 69 Legacy EQ: Authorized for all devices" },
  { raw: "UAD Neve 1081 EQ: Authorized for all devices" },
  { raw: "UAD Neve 33609 Stereo Limiter Compressor: Authorized for all devices" },
  { raw: "UAD Neve 1073 Legacy EQ: Authorized for all devices" },
  { raw: "UAD Precision Multiband Compressor: Authorized for all devices" },
  { raw: "UAD Precision Equalizer: Authorized for all devices" },
  { raw: "UAD EMT 140 Plate Reverb: Authorized for all devices" },
  { raw: "UAD Precision Limiter: Authorized for all devices" },
  { raw: "UAD Softube Amp Room Half-Stack: Demo not started" },
  { raw: "UAD Softube Bass Amp Room 8x10: Demo not started" },
  { raw: "UAD Teletronix LA-2A Legacy Leveler: Authorized for all devices" },
  { raw: "UAD UA 1176LN Legacy Limiter: Authorized for all devices" },
  { raw: "UAD UA 1176SE Legacy Limiter: Authorized for all devices" },
  { raw: "UAD Pultec-Pro Legacy EQ: Authorized for all devices" },
  { raw: "UAD Fairchild 670 Legacy Limiter: Authorized for all devices" },
  { raw: "UAD DreamVerb Room Modeler: Authorized for all devices" },
  { raw: "UAD Cambridge EQ: Authorized for all devices" },
  { raw: "UAD RealVerb-Pro Room Modeler: Authorized for all devices" },
  { raw: "UAD Pultec EQP-1A Legacy EQ: Authorized for all devices" },
  { raw: "UAD Precision Mix Rack Collection: Authorized for all devices" },
  { raw: "UAD Roland RE-201 Tape Delay: Demo expired" },
  { raw: "UAD Roland Dimension D Chorus: Demo not started" },
  { raw: "UAD Roland CE-1 Chorus: Demo not started" }
];

const parsedUserList = userPlugins.map(p => {
  const parts = p.raw.split(':');
  const name = parts[0].trim();
  const status = parts[1].trim();
  return { name, status };
});

// Load the actual UAD database
const uadDbContent = fs.readFileSync('src/data/uadDatabase.ts', 'utf8');

// We can import UAD_DATABASE inside tsx or parse it here.
// Let's print out basic statistics or run a match.
console.log(`Parsed user list count: ${parsedUserList.length}`);
console.log(`First user item: Name: "${parsedUserList[0].name}", Status: "${parsedUserList[0].status}"`);

// Let's see how many of these exist exactly as displayNames in src/data/uadDatabase.ts
let foundCount = 0;
let missing = [];
parsedUserList.forEach(p => {
  const regex = new RegExp(`displayName\\s*:\\s*["'\`]${escapeRegExp(p.name)}["'\`]`, 'i');
  if (regex.test(uadDbContent)) {
    foundCount++;
  } else {
    missing.push(p);
  }
});

console.log(`Exact Match DisplayName count: ${foundCount}`);
console.log(`Missing count: ${missing.length}`);
if (missing.length > 0) {
  console.log('Sample missing:', missing.slice(0, 10));
}

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
