export const ARTIST_EXAMPLES = [
  "Travis Scott", "Drake", "The Weeknd", "Kendrick Lamar", "Kanye West",
  "Taylor Swift", "Bad Bunny", "Billie Eilish", "Post Malone", "Dua Lipa",
  "Ariana Grande", "Ed Sheeran", "Justin Bieber", "Bruno Mars", "Eminem",
  "J. Cole", "Future", "Playboi Carti", "Lil Uzi Vert", "Tyler, The Creator",
  "A$AP Rocky", "21 Savage", "Metro Boomin", "Lil Baby", "Gunna",
  "Young Thug", "Jay-Z", "Nas", "Notorious B.I.G.", "Tupac",
  "Snoop Dogg", "Dr. Dre", "50 Cent", "Lil Wayne", "Nicki Minaj",
  "Cardi B", "Megan Thee Stallion", "Doja Cat", "Mac Miller", "Juice WRLD",
  "XXXTentacion", "Pop Smoke", "Chief Keef", "Migos", "Quavo",
  "Offset", "Takeoff", "Rick Ross", "Meek Mill", "DaBaby",
  "Polo G", "Lil Durk", "NLE Choppa", "Roddy Ricch", "Jack Harlow",
  "Logic", "G-Eazy", "Machine Gun Kelly", "Kid Cudi", "Big Sean",
  "A Boogie wit da Hoodie", "Don Toliver", "Nav", "Yeat", "Ken Carson",
  "Destroy Lonely", "Central Cee", "Skepta", "Stormzy", "Dave",
  "Olivia Rodrigo", "Harry Styles", "Shawn Mendes", "Charlie Puth", "Zayn",
  "Liam Payne", "Niall Horan", "Louis Tomlinson", "Miley Cyrus", "Selena Gomez",
  "Demi Lovato", "Katy Perry", "Lady Gaga", "Rihanna", "Beyoncé",
  "Frank Ocean", "SZA", "Kehlani", "Summer Walker", "Jhené Aiko",
  "H.E.R.", "Bryson Tiller", "Brent Faiyaz", "Giveon", "Daniel Caesar",
  "Khalid", "6LACK", "PARTYNEXTDOOR", "Ty Dolla $ign", "Chris Brown",
  "Usher", "Trey Songz", "Ne-Yo", "Jason Derulo", "The Kid LAROI",
  "Blackbear", "Bazzi", "Lauv", "Troye Sivan", "Conan Gray",
  "Joji", "PinkPantheress", "Daft Punk", "Skrillex", "Diplo",
  "Calvin Harris", "David Guetta", "Martin Garrix", "Tiësto", "Avicii",
  "Zedd", "The Chainsmokers", "Marshmello", "DJ Snake", "Kygo",
  "Alan Walker", "Flume", "Disclosure", "ODESZA", "RÜFÜS DU SOL",
  "Fred again..", "Four Tet", "Skream", "Benga", "Burial",
  "Aphex Twin", "Deadmau5", "Kaskade", "Illenium", "Porter Robinson",
  "Madeon", "San Holo", "Rezz", "Alison Wonderland", "RL Grime",
  "Baauer", "DJ Shadow", "Flying Lotus", "Kaytranada", "SG Lewis",
  "Channel Tres", "Peggy Gou", "Fisher", "Chris Lake", "Dom Dolla",
  "John Summit", "James Hype", "CamelPhat", "Gorgon City", "Bicep",
  "Tale Of Us", "Amelie Lens", "J Balvin", "Maluma", "Ozuna",
  "Daddy Yankee", "Anuel AA", "Rauw Alejandro", "Myke Towers", "El Alfa",
  "Sech", "Feid", "Karol G", "Becky G", "Natti Natasha",
  "Rosalía", "C. Tangana", "Bizarrap", "Duki", "Tiago PZK",
  "Trueno", "Peso Pluma", "Natanael Cano", "Eslabon Armado", "Fuerza Regida",
  "Grupo Frontera", "Shakira", "Enrique Iglesias", "Ricky Martin", "Marc Anthony",
  "Romeo Santos", "Aventura", "Prince Royce", "Burna Boy", "Wizkid",
  "Davido", "Rema", "Asake", "Tyla", "Ayra Starr",
  "CKay", "Fireboy DML", "Omah Lay", "Tems", "Amaarae",
  "Blackpink", "BTS", "NewJeans", "Stray Kids", "TWICE",
  "SEVENTEEN", "Rosé", "Lisa", "Jennie", "Jisoo"
];
