export const COMMON_PLUGIN_MAPPING: Record<string, { type: string, description: string }> = {
  // Instruments
  'serum': { type: 'Instruments', description: 'Advanced wavetable synthesizer with high-quality sound and visual workflow.' },
  'omnisphere': { type: 'Instruments', description: 'Flagship synthesizer with massive library and deep synthesis capabilities.' },
  'kontakt': { type: 'Instruments', description: 'Industry-standard sampler with a vast library of instruments.' },
  'sylenth1': { type: 'Instruments', description: 'Virtual analog VSTi synthesizer known for its warmth and clarity.' },
  'nexus': { type: 'Instruments', description: 'ROM synthesizer featuring high-quality sounds for electronic music.' },
  'vital': { type: 'Instruments', description: 'Spectral warping wavetable synthesizer.' },
  'diva': { type: 'Instruments', description: 'Virtual analog synthesizer that captures the spirit of various classic synths.' },
  'spire': { type: 'Instruments', description: 'Polyphonic software synthesizer that combines powerful sound engine modulation.' },
  'phase plant': { type: 'Instruments', description: 'Modular synthesizer with limitless sound design possibilities.' },
  'pigments': { type: 'Instruments', description: 'Polychrome software synthesizer with multiple synthesis engines.' },
  'keyscape': { type: 'Instruments', description: 'Collector keyboards virtual instrument with rare and restored pianos.' },
  'trilian': { type: 'Instruments', description: 'Total bass module featuring acoustic, electric, and synth basses.' },
  'analog lab': { type: 'Instruments', description: 'Massive collection of classic synth and keyboard sounds.' },
  'v collection': { type: 'Instruments', description: 'Arturia collection of legendary vintage synthesizers.' },
  'arcade': { type: 'Instruments', description: 'Loop synthesizer with creative manipulation tools.' },
  
  // Equalizers
  'pro-q 3': { type: 'Equalizers', description: 'High-quality EQ plugin with perfect analog matching and dynamic EQ.' },
  'gullfoss': { type: 'Equalizers', description: 'Intelligent EQ that uses computational auditory perception.' },
  'api 550': { type: 'Equalizers', description: 'Classic American console EQ emulation.' },
  'api 560': { type: 'Equalizers', description: 'Graphic EQ with unique "Proportional Q" circuitry.' },
  'puigtec': { type: 'Equalizers', description: 'Emulation of the legendary Pultec EQP-1A and MEQ-5.' },
  'ssl-e channel': { type: 'Equalizers', description: 'Solid State Logic E-Series console channel strip.' },
  'ssl-g channel': { type: 'Equalizers', description: 'Solid State Logic G-Series console channel strip.' },
  'h-eq': { type: 'Equalizers', description: 'Hybrid equalizer featuring vintage and modern EQ characteristics.' },
  'neutron 4 eq': { type: 'Equalizers', description: 'Intelligent equalizer with masking detection.' },
  'ozone 9 eq': { type: 'Equalizers', description: 'Mastering grade equalizer with digital and analog modes.' },
  'ozone 10 eq': { type: 'Equalizers', description: 'Mastering grade equalizer with digital and analog modes.' },
  'ozone 11 eq': { type: 'Equalizers', description: 'Mastering grade equalizer with digital and analog modes.' },

  // Dynamics
  'pro-c 2': { type: 'Dynamics', description: 'High-quality compressor plugin with versatile routing and sidechaining.' },
  'pro-l 2': { type: 'Dynamics', description: 'Feature-packed true peak limiter plugin.' },
  'cla-76': { type: 'Dynamics', description: 'Classic FET compressor emulation.' },
  'cla-2a': { type: 'Dynamics', description: 'Classic opto compressor emulation.' },
  'cla-3a': { type: 'Dynamics', description: 'Solid-state opto compressor emulation.' },
  'soothe2': { type: 'Dynamics', description: 'Dynamic resonance suppressor that removes harshness automatically.' },
  'rvox': { type: 'Dynamics', description: 'Renaissance Vox - simple and powerful vocal compressor.' },
  'rcompressor': { type: 'Dynamics', description: 'Renaissance Compressor - warm, musical compression.' },
  'l2 limiter': { type: 'Dynamics', description: 'The industry standard ultra-maximizer limiter.' },
  'l1 limiter': { type: 'Dynamics', description: 'Classic peak limiter and maximizer.' },
  'l3-ll': { type: 'Dynamics', description: 'Multiband peak limiter with low latency.' },
  'ott': { type: 'Dynamics', description: 'Aggressive multiband upwards/downwards compressor.' },
  'shadow hills': { type: 'Dynamics', description: 'Mastering compressor with multiple transformer stages.' },
  'vulf compressor': { type: 'Dynamics', description: 'Lo-fi compression with unique character.' },
  'neutron 4 compressor': { type: 'Dynamics', description: 'Intelligent compressor with multiple modes.' },
  'ozone 9 maximizer': { type: 'Dynamics', description: 'Intelligent mastering limiter.' },
  'ozone 10 maximizer': { type: 'Dynamics', description: 'Intelligent mastering limiter.' },
  'ozone 11 maximizer': { type: 'Dynamics', description: 'Intelligent mastering limiter.' },

  // Reverb & Delay
  'valhalla': { type: 'Reverb & Delay', description: 'High-quality reverb or delay effect.' },
  'echoboy': { type: 'Reverb & Delay', description: 'The ultimate creative delay plugin.' },
  'h-delay': { type: 'Reverb & Delay', description: 'Hybrid delay with vintage character and modern control.' },
  'pro-r': { type: 'Reverb & Delay', description: 'Natural sounding algorithmic reverb with intuitive controls.' },
  'altiverb': { type: 'Reverb & Delay', description: 'Industry standard convolution reverb.' },
  'seventh heaven': { type: 'Reverb & Delay', description: 'Bricasti M7 convolution reverb emulation.' },
  'raum': { type: 'Reverb & Delay', description: 'Creative algorithmic reverb for space and texture.' },
  'replika': { type: 'Reverb & Delay', description: 'Versatile delay with multiple modes and modulation.' },
  'crystallizer': { type: 'Reverb & Delay', description: 'Granular echo synthesizer for otherworldly textures.' },

  // Distortion & Saturation
  'decapitator': { type: 'Distortion & Saturation', description: 'Analog saturation modeler that brings hardware character to digital tracks.' },
  'saturn': { type: 'Distortion & Saturation', description: 'Multiband distortion, saturation and amplifier modeling plugin.' },
  'radiator': { type: 'Distortion & Saturation', description: 'Tube preamp and EQ based on the Altec 1567A.' },
  'devil-loc': { type: 'Distortion & Saturation', description: 'Aggressive crushing compressor and distortion.' },
  'trash 2': { type: 'Distortion & Saturation', description: 'Ultimate distortion and mangling plugin.' },
  'black box': { type: 'Distortion & Saturation', description: 'Analog tube saturation and enhancement.' },
  'thermal': { type: 'Distortion & Saturation', description: 'Interactive distortion plugin with multi-stage processing.' },
  'ssl': { type: 'Dynamics', description: 'Solid State Logic console emulations (Channel Strip, Bus Compressor).' },
  'neve': { type: 'Equalizers', description: 'Classic British console emulations (1073, 1081, etc.).' },

  // Modulation
  'microshift': { type: 'Modulation', description: 'Classic widening and thickening effect.' },
  'chorus-dimension d': { type: 'Modulation', description: 'Classic 80s spatial enhancer.' },
  'metaflanger': { type: 'Modulation', description: 'Versatile flanging and chorusing effect.' },
  'brauer motion': { type: 'Modulation', description: 'Circular panner for movement and depth.' },
  'mondomod': { type: 'Modulation', description: 'Combination of AM, FM, and rotation for complex modulation.' },

  // Utility & Metering
  'span': { type: 'Utility & Metering', description: 'Free real-time fast Fourier transform audio spectrum analyzer.' },
  'insight': { type: 'Utility & Metering', description: 'Comprehensive metering and audio analysis suite.' },
  'metric ab': { type: 'Utility & Metering', description: 'The ultimate reference plugin for comparing mixes.' },
  'youlean': { type: 'Utility & Metering', description: 'Loudness meter for mastering.' },
  'tonal balance control': { type: 'Utility & Metering', description: 'Visualizes the spectral balance of your mix.' },

  // Creative FX
  'rc-20': { type: 'Creative FX', description: 'Creative effect plugin that adds life and texture inspired by classic gear.' },
  'auto-tune': { type: 'Creative FX', description: 'The industry standard for professional pitch correction.' },
  'little alterboy': { type: 'Creative FX', description: 'Monophonic voice manipulator for pitch and formant shifting.' },
  'halftime': { type: 'Creative FX', description: 'Instant half-speed effect for creating dark, down-tempo vibes.' },
  'gross beat': { type: 'Creative FX', description: 'Time and volume manipulation effect.' },
  'shaperbox': { type: 'Creative FX', description: 'Rhythmic effects plugin for modern mix manipulation.' },
  'portal': { type: 'Creative FX', description: 'Granular synthesis effect plugin for transforming audio.' },
  'melodyne': { type: 'Creative FX', description: 'Advanced pitch and time correction with polyphonic capabilities.' },
  'nectar': { type: 'Creative FX', description: 'Complete vocal processing suite with pitch, EQ, and dynamics.' },
  'avox': { type: 'Creative FX', description: 'Vocal processing suite for character and texture.' },
  'vocalign': { type: 'Creative FX', description: 'The industry standard for aligning vocal tracks.' },
  'effectrix': { type: 'Creative FX', description: 'Sequenced multi-effects for rhythmic manipulation.' },
  'looperator': { type: 'Creative FX', description: 'Slices up your audio and turns it into something new.' },
  'kickstart': { type: 'Dynamics', description: 'Nicky Romero Kickstart - sidechain compression effect.' },
  'shaper': { type: 'Creative FX', description: 'Cableguys ShaperBox - rhythmic effects.' },
  'half time': { type: 'Creative FX', description: 'Half-speed effect.' },
  'infiltrator': { type: 'Creative FX', description: 'Advanced multi-effect sequencer.' },
  'movement': { type: 'Creative FX', description: 'Rhythmic engine for adding motion to any sound.' },
  'sublab': { type: 'Instruments', description: 'Sub-bass synthesizer.' },
  'ana 2': { type: 'Instruments', description: 'Powerful wavetable synthesizer.' },
  'avenger': { type: 'Instruments', description: 'Vengeance Producer Suite - Avenger synthesizer.' },
  'massive': { type: 'Instruments', description: 'Native Instruments Massive - wavetable synthesizer.' },
  'monark': { type: 'Instruments', description: 'Monophonic analog synthesizer emulation.' },
  'reark': { type: 'Instruments', description: 'Polyphonic synthesizer.' },
  'fm8': { type: 'Instruments', description: 'FM synthesizer.' },
  'absynth': { type: 'Instruments', description: 'Semi-modular synthesizer.' },
  'battery': { type: 'Instruments', description: 'Professional drum sampler.' },
  'polyplex': { type: 'Instruments', description: 'Eight-part drum sampler.' },
  'form': { type: 'Instruments', description: 'Transformative sample-based synthesizer.' },
  'rounds': { type: 'Instruments', description: 'Sequence and morphing synthesizer.' },
  'kontour': { type: 'Instruments', description: 'Phase modulation synthesizer.' },
  'super 8': { type: 'Instruments', description: 'Modern polyphonic synth.' },

  // Vendors
  'fabfilter': { type: 'Equalizers', description: 'High-quality audio plugins from FabFilter.' },
  'soundtoys': { type: 'Creative FX', description: 'Creative audio effects from Soundtoys.' },
  'waves': { type: 'Dynamics', description: 'Professional audio plugins from Waves.' },
  'izotope': { type: 'Utility & Metering', description: 'Audio software from iZotope.' },
  'arturia': { type: 'Instruments', description: 'Software instruments and effects from Arturia.' },
  'native instruments': { type: 'Instruments', description: 'Software instruments and effects from Native Instruments.' },
  'u-he': { type: 'Instruments', description: 'High-quality synthesizers and effects from u-he.' },
  'spectrasonics': { type: 'Instruments', description: 'Flagship virtual instruments from Spectrasonics.' },
  'xfer': { type: 'Instruments', description: 'Innovative audio software from Xfer Records.' },
  'output': { type: 'Creative FX', description: 'Creative software instruments and effects from Output.' },

  // Generic Keywords (Fallbacks)
  'synth': { type: 'Instruments', description: 'Software synthesizer.' },
  'instrument': { type: 'Instruments', description: 'Virtual instrument.' },
  'sampler': { type: 'Instruments', description: 'Audio sampler.' },
  'piano': { type: 'Instruments', description: 'Virtual piano instrument.' },
  'keyboard': { type: 'Instruments', description: 'Keyboard instrument.' },
  'compressor': { type: 'Dynamics', description: 'Dynamic range compressor.' },
  'limiter': { type: 'Dynamics', description: 'Audio limiter.' },
  'gate': { type: 'Dynamics', description: 'Noise gate or rhythmic gate.' },
  'equalizer': { type: 'Equalizers', description: 'Audio equalizer.' },
  ' eq ': { type: 'Equalizers', description: 'Audio equalizer.' },
  'reverb': { type: 'Reverb & Delay', description: 'Reverb effect.' },
  'delay': { type: 'Reverb & Delay', description: 'Delay or echo effect.' },
  'echo': { type: 'Reverb & Delay', description: 'Echo effect.' },
  'distortion': { type: 'Distortion & Saturation', description: 'Distortion effect.' },
  'saturation': { type: 'Distortion & Saturation', description: 'Saturation effect.' },
  'overdrive': { type: 'Distortion & Saturation', description: 'Overdrive effect.' },
  'chorus': { type: 'Modulation', description: 'Chorus effect.' },
  'flanger': { type: 'Modulation', description: 'Flanger effect.' },
  'phaser': { type: 'Modulation', description: 'Phaser effect.' },
  'tremolo': { type: 'Modulation', description: 'Tremolo effect.' },
  'meter': { type: 'Utility & Metering', description: 'Audio metering tool.' },
  'analyzer': { type: 'Utility & Metering', description: 'Audio analysis tool.' }
};
